# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Shows the shows the current user name
[username]
format = "[$user](yellow)"
disabled = false
show_always = true

# Shows the current host name
[hostname]
ssh_only = false
format = "@[$hostname](red) "
trim_at = ""
disabled = false

# Replace the "â¯" symbol in the prompt
# [character]
# success_symbol = "[>>](bold green)"
# error_symbol = "[>>](bold red)"
