# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Shows the time
[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%R"

# Shows the shows the current user name
[username]
format = "[$user](bold yellow)"
disabled = false
show_always = true

# Shows the current host name
[hostname]
ssh_only = false
format = "@[$hostname](bold red) "
trim_at = ""
disabled = false

# Changes the git status default format
# [git_status]
# conflicted = "ğŸ³"
# ahead = "ğŸğŸ’¨"
# behind = "ğŸ˜°"
# diverged = "ğŸ˜µ"
# up_to_date = "âœ“"
# untracked = "ğŸ¤·"
# stashed = "ğŸ“¦"
# modified = "ğŸ“"
# staged = '[++\($count\)](green)'
# renamed = "ğŸ‘…"
# deleted = "ğŸ—‘"

# Replace the "â¯" symbol in the prompt
# [character]
# success_symbol = "[>>](bold green)"
# error_symbol = "[>>](bold red)"
