# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt
# [character]
# success_symbol = "[>>](bold green)"
# error_symbol = "[>>](bold red)"
